### ISSUE TITLE
Unable to connect to drone

### ISSUE THREAD

**Issue by cvmutian** [andriyukr/olympe_bridge#3]
Hi, andriy, excellent work on ros2 and anafi drone!
I tried running your code, but I have some trouble when connecting to the drone.
I configured the same experimental environment as you and successfully completed the compilation, but when I run the launch file in the terminal, it remains in a "connecting" state and cannot establish a successful connection.I wonder about the possible reasons for this situation.
Thank you for any help!

**Comment by andriyukr** [comment]
There might be several causes of the connection issue. You have to go by exclusion to identify it.
Here are some potential causes and possible solutions:

1. **Skycontroller-Drone connection problem**: check whether skycontroller is paired and connected to the drone. Turn on both skycontroller and Anafi, and try to pan the gimbal. If it works, then they are connected.
2. **Skycontroller-PC connection problem**: check whether skycontroller is properly connected to your PC. In the terminal, write _ifconfig_ and check whether there is a USB device with _192.168.53.1_ IP address. If yes, then the connection is fine.
3. **Wifi key problem**: try to connect to the default paired Anafi. You are trying to connect to Anafi with a specific SN and WIFI key. Instead, I recommend connecting to the paired Anafi. So, just leave SN and WIFI key in the launch file blank.

I hope this will solve your issue.
