### ISSUE TITLE
Nothing happend 

### ISSUE THREAD

**Issue by YHuniv** [andriyukr/olympe_bridge#4]
Hi 
I am trying to use your ROS package for Anafi 4k.
All instalaltions are good.

When I run :
**roslaunch olympe_bridge anafi.launch**
I get : 

SUMMARY
========

PARAMETERS
 * /anafi/drone_serial: **I delete it**
 * /anafi/ip: 192.168.42.1
 * /anafi/model: 4k
 * /anafi/name: anafi
 * /anafi/rest_api_version: 1
 * /anafi/skycontroller_enabled: True
 * /anafi/wifi_key: **I delete it**
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /anafi/
    anafi (olympe_bridge/anafi)
    set_anafi_log_level (rosservice/rosservice)

auto-starting new master
process[master]: started with pid [12635]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f6afa2f8-fa15-11ed-a6bf-598011ea070e
process[rosout-1]: started with pid [12660]
started core service [/rosout]
process[anafi/set_anafi_log_level-2]: started with pid [12667]
process[anafi/anafi-3]: started with pid [12668]
[INFO] [1684920778.876837] [/anafi/anafi]: Anafi_bridge is running...
[INFO] [1684920778.931761] [/anafi/anafi]: Connecting through SkyController
[INFO] [1684920778.984018] [/anafi/anafi]: Connecting to **I delete it** with **I delete it**
[anafi/set_anafi_log_level-2] process has finished cleanly
log file: /home/zoe/.ros/log/f6afa2f8-fa15-11ed-a6bf-598011ea070e/anafi-set_anafi_log_level-2*.log

after that nothing happened and **rostopic echo /anafi/battery/voltage** for example  give nothing too.

Did I miss somthing ? I tried with skycontroller on and tried off. same thing.

THanks by advance

**Comment by andriyukr** [comment]
It looks like the skycontroller does not connect to the drone. Try to connect to the default paired Anafi. If I got it correctly, you are trying to connect to Anafi with a specific SN and WIFI key. Instead, I recommend connecting to the default paired Anafi. So, just leave SN and WIFI key in the launch file blank as in the original file.

**Comment by YHuniv** [comment]
I started from beginning and leave all by defaults but stil same issue.
**cd ~/anafi_ws/src
git clone -b ros1 https://github.com/andriyukr/anafi_ros.git
sudo chmod -R 777 anafi_ros/
catkin_make
roslaunch olympe_bridge anafi.launch
**


SUMMARY
========

PARAMETERS
 * /anafi/drone_serial: 
 * /anafi/ip: 192.168.53.1
 * /anafi/model: 4k
 * /anafi/name: anafi
 * /anafi/rest_api_version: 1
 * /anafi/skycontroller_enabled: True
 * /anafi/wifi_key: 
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /anafi/
    anafi (olympe_bridge/anafi)
    set_anafi_log_level (rosservice/rosservice)

auto-starting new master
process[master]: started with pid [5894]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 39bdc9f2-fa1c-11ed-a712-29a53f2a02fd
process[rosout-1]: started with pid [5920]
started core service [/rosout]
process[anafi/set_anafi_log_level-2]: started with pid [5927]
process[anafi/anafi-3]: started with pid [5928]
[INFO] [1684923468.381037] [/anafi/anafi]: Anafi_bridge is running...
[INFO] [1684923468.535817] [/anafi/anafi]: Connecting through SkyController
[anafi/set_anafi_log_level-2] process has finished cleanly
log file: /home/zoe/.ros/log/39bdc9f2-fa1c-11ed-a712-29a53f2a02fd/anafi-set_anafi_log_level-2*.log

**Comment by andriyukr** [comment]
Check the reply to this issue: https://github.com/andriyukr/anafi_ros/issues/3#issuecomment-1560812643

**Comment by YHuniv** [comment]
THanks, now it's working.

I didnt undurnsdunfd before that  Skycontroller sould be connected to PC with usb cable.

**2.Skycontroller-PC connection problem: check whether skycontroller is properly connected to your PC. In the terminal, write ifconfig and check whether there is a USB device with 192.168.53.1 IP address. If yes, then the connection is fine.**
