### ISSUE TITLE
Olympe 7.5 and firmware

### ISSUE THREAD

**Issue by jack-Singapore** [andriyukr/olympe_bridge#8]
Hi Andri, Would like to know which firmware version of Anafi AI is compatible with the anafi_ros?
Could we use the olympe 7.7 with this ros2 package?

Thanks 
Regards

**Comment by andriyukr** [comment]
Hi,

The package was tested with Olympe 7.5.
Some minor changes might be required to make it compatible with Olympe 7.7. We can verify this and come back to you.

Best,
Andriy

**Comment by jack-Singapore** [comment]
Thanks for the reply.
Node crashed when cloned and ran. To succesfully run, i add below codes to the anafi.py
Added this to line 876,

```python
if self.model == 'ai' and vmeta[1]['links'] != []:  # TODO: check to which network the drone is connected (wlan or cellular)
	if 'starfish' in vmeta[1]['links'][0]:
		msg_quality = UInt8()
		msg_quality.data = vmeta[1]['links'][0]['starfish']['quality']  # [0=bad, 5=good]
		self.pub_link_quality.publish(msg_quality)
	elif 'wifi' in vmeta[1]['links'][0]:
		msg_quality = UInt8()
		msg_quality.data = vmeta[1]['links'][0]['wifi']['quality']  # [0=bad, 5=good]
		self.pub_link_quality.publish(msg_quality)
	else:
		self.node.get_logger().fatal("The model is NOT '" + self.model + "'")
		self.disconnect()
		rclpy.shutdown()
		exit()
```

could i ask what is the difference between drone/rth and home/navigate service?
Thanks Andriy

**Comment by andriyukr** [comment]
The main difference between these two services is in the SDK functions they call: `drone/rth` calls [return_to_home()](https://developer.parrot.com/docs/olympe/arsdkng_rth.html#olympe.messages.rth.return_to_home) from the rth class and `home/navigate` calls [NavigateHome()](https://developer.parrot.com/docs/olympe/arsdkng_ardrone3_piloting.html#olympe.messages.ardrone3.Piloting.NavigateHome) from the Piloting class. Hovewer, their behavior should be identical.

**Comment by andriyukr** [comment]
We tested the package with the latest Olympe **7.7.5** on ANAFI Ai, and it works properly.
