### ISSUE TITLE
flatbuffers error

### ISSUE THREAD

**Issue by eee-Andrew** [andriyukr/olympe_bridge#9]
$ pip install parrot-olympe==7.5.0
.
.
.
Successfully built asn1tools

WARNING: Error parsing dependencies of flatbuffers: Invalid version: '1.12.1-git20200711.33e2d80-dfsg1-0.6'

Installing collected packages: wcwidth, pure-eval, aenum, tzlocal, typing-extensions, traitlets, tomli, pycryptodomex, protobuf, prompt-toolkit, platformdirs, pathspec, parso, mypy-extensions, geographiclib, executing, exceptiongroup, dacite, colorlog, boltons, bitstruct, asttokens, stack-data, matplotlib-inline, jedi, geopy, black, asn1tools, ipython, parrot-olympe
Successfully installed aenum-3.1.15 asn1tools-0.167.0 asttokens-2.4.1 bitstruct-8.19.0 black-24.10.0 boltons-24.1.0 colorlog-6.9.0 dacite-1.8.1 exceptiongroup-1.2.2 executing-2.1.0 geographiclib-2.0 geopy-2.4.1 ipython-8.29.0 jedi-0.19.2 matplotlib-inline-0.1.7 mypy-extensions-1.0.0 parrot-olympe-7.5.0 parso-0.8.4 pathspec-0.12.1 platformdirs-4.3.6 prompt-toolkit-3.0.48 protobuf-3.19.4 pure-eval-0.2.3 pycryptodomex-3.21.0 stack-data-0.6.3 tomli-2.1.0 traitlets-5.14.3 typing-extensions-4.12.2 tzlocal-3.0 wcwidth-0.2.13

**Comment by andriyukr** [comment]
This issue is related to the Olympe, not to the anafi_ros package.
